version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=redmine
      - POSTGRES_USER=redmine
      - POSTGRES_PASSWORD=pa33word
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redmine:
    image: redmine:latest
    depends_on:
      - postgres
    environment:
      - REDMINE_DB_POSTGRES=postgres
      - REDMINE_DB_DATABASE=redmine
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=pa33word
    ports:
      - 8080:3000
    volumes:
      - redmine_data:/usr/src/redmine/files

volumes:
  postgres_data:
  redmine_data: