version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=hasura
      - POSTGRES_USER=hasura
      - POSTGRES_PASSWORD=pa33word
    volumes:
      - postgres_data:/var/lib/postgresql/data

  graphql-engine:
    image: hasura/graphql-engine:latest
    depends_on:
      - postgres
    environment:
      - HASURA_GRAPHQL_METADATA_DATABASE_URL=postgres://hasura:pa33word@postgres:5432/hasura
      - HASURA_GRAPHQL_DATABASE_URL=postgres://hasura:pa33word@postgres:5432/hasura
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_ADMIN_SECRET=secret
    ports:
      - 8080:8080

volumes:
  postgres_data: